#!/usr/bin/env bash

set -euo pipefail

SERVER="selrak@yshitbox"
REMOTE_DIR="/home/selrak/Documents/shared/"
LOCAL_DIR="$HOME/debianShare/"

mkdir -p "$LOCAL_DIR"

rsync -avz --progress \
    "$SERVER:$REMOTE_DIR" \
    "$LOCAL_DIR"
